### PR TITLE
[DRAFT] Add basic handling of syscalls

### LINKED ISSUE #198: [SYSCALLS] Syscall layer bootstrap
* Allocate interrupt number 
* Create idt entry  (it needs to have dpl = 3)
* update idt exception handler
* create handling function for the syscall

### PR DESCRIPTION
**Pull request by dreamos82**
Close #198

### CODE REVIEW

File: src/kernel/framebuffer/framebuffer.c [hunk 1]
```diff
@@ -199,6 +199,16 @@ void _fb_printStrAndNumberAt(const char *string, uint64_t number, size_t cx, siz
...
 
+/**
+ * This function return the hhdm pointer of the physycal address provided
+ *
+ *
+ * @param pixels_w this parameter will contain the width in pixels
+ * @param pixels_h this parameter will contain the height in pixels
+ * @param chars_w this parameter will contain the number of columns according to the char loaded
+ * @param chars_h this parameter will contain the number of rows according to the char loaded
+ * @return hhdm virtual address of the physical address or NULL in case of error
```
Comment (DeanoBurrito) [inline src/kernel/framebuffer/framebuffer.c:210]: this function does not return anything (yet?) 🤔

Comment (dreamos82) [reply src/kernel/framebuffer/framebuffer.c:210]: ahaha yeah... 
copy and paste hit again!
